// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omlippsflxidjbdsyjbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tbGlwcHNmbHhpZGpiZHN5amJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTY0ODYsImV4cCI6MjA1Nzc3MjQ4Nn0.fnzw4owURDInEckmp4CiBmS-dWRj5N3dS1Ui36DaIhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the Supabase client with additional logging
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a health check function to test the connection
export const checkSupabaseConnection = async () => {
  try {
    // Try a simple query to test the connection
    const { data, error } = await supabase.from('system_settings').select('key').limit(1);
    
    if (error) {
      console.error('Supabase connection error:', error);
      return { connected: false, error: error.message };
    }
    
    return { connected: true, data };
  } catch (err) {
    console.error('Failed to connect to Supabase:', err);
    return { connected: false, error: err instanceof Error ? err.message : 'Unknown error' };
  }
};